name: Scheduled Script Run

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        pip install requests
        
    - name: Run the script
      run: python merge.py

    - name: Check for changes
      id: git-check
      run: |
        git status --porcelain
        echo "::set-output name=modified::$(if git status --porcelain | grep .; then echo true; else echo false; fi)"

    - name: Commit and Push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git status
        git commit -m "Update merged file" -a || echo "No changes to commit"
        git push || echo "Push failed"
        echo "Current branch:"
        git branch --show-current
        echo "Latest commit:"
        git log -1

    - name: No changes
      if: steps.git-check.outputs.modified == 'false'
      run: echo "No changes to commit"
